# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 12:44
from __future__ import unicode_literals

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='class_detail',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
    ]
