# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='issue',
            field=models.CharField(default='Default', max_length=50),
            preserve_default=False,
        ),
    ]
